'use client'
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { FileText, Download, Clock, CheckCircle, XCircle, Loader, AlertCircle, Trash2 } from 'lucide-react'
import { reportsApi } from '@/lib/api'
import { Report } from '@/types'
import { useToast } from '@/lib/providers'

const statusConfig = {
  pending: { icon: Clock, color: '#FFB547', label: 'Pending Queue' },
  generating: { icon: Loader, color: '#18C8FF', label: 'Generating PDF...' },
  ready: { icon: CheckCircle, color: '#27D980', label: 'Ready for Export' },
  failed: { icon: XCircle, color: '#FF5A6E', label: 'Generation Failed' },
}

export default function ReportsPage() {
  const qc = useQueryClient()
  const { showToast, confirm } = useToast()
  const [downloadingId, setDownloadingId] = useState<string | null>(null)
  const [deletingId, setDeletingId] = useState<string | null>(null)

  const { data: reports = [], isLoading } = useQuery<Report[]>({
    queryKey: ['reports'],
    queryFn: reportsApi.list,
    staleTime: 0,
    refetchOnMount: 'always',
    refetchInterval: (query) => {
      const data = query.state.data as Report[] | undefined
      return data?.some(r => r.status === 'generating' || r.status === 'pending') ? 3000 : false
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (reportId: string) => reportsApi.delete(reportId),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['reports'] })
      showToast('Report deleted successfully.', 'success')
    },
    onError: (e: any) => {
      showToast(e?.response?.data?.detail || 'Failed to delete report.', 'error')
    },
    onSettled: () => {
      setDeletingId(null)
    },
  })

  const handleDownload = async (id: string, title: string) => {
    try {
      setDownloadingId(id)
      await reportsApi.downloadReport(id, title)
      showToast('Report downloaded successfully.', 'success')
    } catch (e: any) {
      showToast(e?.message || e?.response?.data?.detail || 'Failed to download report PDF.', 'error')
    } finally {
      setDownloadingId(null)
    }
  }

  const handleDelete = async (report: Report) => {
    const confirmed = await confirm({
      title: 'Delete Report?',
      message: `Are you sure you want to delete "${report.title}"? This will permanently delete the report record and its generated PDF document on disk.`,
      confirmText: 'Delete Report',
      isDestructive: true,
    })

    if (confirmed) {
      setDeletingId(report.id)
      deleteMutation.mutate(report.id)
    }
  }

  const uniqueReports = Array.from(new Map(reports.map((r) => [r.id, r])).values())

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto text-[#F5FAFC]">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#24475F]/60 pb-5">
        <div>
          <h1 className="font-display text-2xl font-bold text-[#F5FAFC] flex items-center gap-2">
            <FileText className="w-6 h-6 text-[#18C8FF]" />
            EcoRal PDF Reports & Risk Assessments
          </h1>
          <p className="text-xs text-[#8FA6B8] mt-1">
            Downloadable publication-ready Coral Bleaching Vulnerability Reports generated by the EcoRal AI engine.
          </p>
        </div>
      </div>

      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-20 gap-2">
          <div className="w-8 h-8 border-2 border-[#18C8FF]/30 border-t-[#18C8FF] rounded-full animate-spin" />
          <span className="text-xs text-[#8FA6B8] font-medium">Loading report catalog...</span>
        </div>
      ) : uniqueReports.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 rounded-xl border border-dashed border-[#24475F] bg-[#0C1C2A]">
          <FileText className="w-10 h-10 text-[#8FA6B8]/40 mb-3" />
          <p className="text-sm font-bold text-[#F5FAFC]">No PDF Reports Generated Yet</p>
          <p className="text-xs text-[#8FA6B8] mt-1 max-w-sm text-center">
            Run risk predictions from the Dashboard or Ocean Map to generate automated PDF assessment documents.
          </p>
        </div>
      ) : (
        <div className="grid gap-3">
          {uniqueReports.map((report, i) => {
            const cfg = statusConfig[report.status] || statusConfig.pending
            const isDownloading = downloadingId === report.id
            const isDeleting = deletingId === report.id

            return (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.04 }}
                className="flex items-center gap-4 p-4 rounded-xl border border-[#24475F] bg-[#0C1C2A]"
              >
                <div className="w-10 h-10 rounded-lg bg-[#122535] border border-[#24475F] flex items-center justify-center shrink-0">
                  <cfg.icon className="w-5 h-5" style={{ color: cfg.color }} />
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="font-semibold text-[#F5FAFC] text-sm truncate">{report.title}</p>
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-[#1A364A] text-[#8FA6B8] font-mono border border-[#24475F]">
                      ID: {report.id.slice(0, 8)}
                    </span>
                  </div>
                  <div className="flex items-center gap-3 mt-1 text-xs">
                    <span className="font-semibold" style={{ color: cfg.color }}>{cfg.label}</span>
                    <span className="text-[#8FA6B8]">•</span>
                    <span className="text-[#8FA6B8]">{new Date(report.created_at).toLocaleString()}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {report.status === 'ready' && (
                    <button
                      onClick={() => handleDownload(report.id, report.title)}
                      disabled={isDownloading || isDeleting}
                      className="flex items-center gap-2 px-3.5 py-1.5 rounded-lg border border-[#27D980]/30 bg-[#27D980]/10 text-[#27D980] text-xs font-bold hover:bg-[#27D980]/20 transition-all cursor-pointer shadow-sm disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <Loader className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <Download className="w-3.5 h-3.5" />
                      )}
                      <span>{isDownloading ? 'Downloading...' : 'Download PDF'}</span>
                    </button>
                  )}

                  <button
                    onClick={() => handleDelete(report)}
                    disabled={isDownloading || isDeleting}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[#FF5A6E]/30 bg-[#FF5A6E]/10 text-[#FF5A6E] text-xs font-bold hover:bg-[#FF5A6E]/20 transition-all cursor-pointer shadow-sm disabled:opacity-50"
                  >
                    {isDeleting ? (
                      <Loader className="w-3.5 h-3.5 animate-spin" />
                    ) : (
                      <Trash2 className="w-3.5 h-3.5" />
                    )}
                    <span>{isDeleting ? 'Deleting...' : 'Delete'}</span>
                  </button>
                </div>
              </motion.div>
            )
          })}
        </div>
      )}
    </div>
  )
}
